name: CI
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.17"
          - "1.16"
    steps:
      - name: Set up Go ${{ matrix.go }}
        users: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        users: codecov/codecov-action@v2
        if: matrix.go == '1.17'
        with:
          files: ./coverage.txt
